# Generated by Django 5.0.4 on 2025-01-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_task_list_user_delete_user_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_list',
            name='descrition',
        ),
        migrations.AddField(
            model_name='task_list',
            name='taskName',
            field=models.CharField(default='', max_length=500),
        ),
    ]
